In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, Normalizer
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.optimizers import Adam

In [2]:
dataset = pd.read_csv("life_expectancy.csv")
dataset.head()

,Country,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,Afghanistan,2015,Developing,263.0,62,0.01,71.279624,65.0,1154,19.1,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,Afghanistan,2014,Developing,271.0,64,0.01,73.523582,62.0,492,18.6,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,Afghanistan,2013,Developing,268.0,66,0.01,73.219243,64.0,430,18.1,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,Afghanistan,2012,Developing,272.0,69,0.01,78.184215,67.0,2787,17.6,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,Afghanistan,2011,Developing,275.0,71,0.01,7.097109,68.0,3013,17.2,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2

In [3]:
dataset.describe()

,Year,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
count,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2.938000e+03,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000
mean,2007.518720,164.725664,30.303948,4.546875,738.251295,83.022124,2419.592240,38.381178,42.035739,82.617767,5.924098,82.393125,1.742103,6611.523863,1.023085e+07,4.821886,4.852144,0.630362,12.009837,69.234717
std,4.613841,124.086215,117.926501,3.921946,1987.914858,22.996984,11467.272489,19.935375,160.445548,23.367166,2.400770,23.655562,5.077785,13296.603449,5.402242e+07,4.397621,4.485854,0.205140,3.265139,9.509115
min,2000.000000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.370000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000,36.300000
25%,2004.000000,74.000000,0.000000,1.092500,4.685343,82.000000,0.000000,19.400000,0.000000,78.000000,4.370000,78.000000,0.100000,580.486996,4.189172e+05,1.600000,1.600000,0.504250,10.300000,63.200000
50%,2008.000000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.755000,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000,72.100000
75%,2012.000000,227.000000,22.000000,7.390000,441.534144,96.000000,360.250000,56.100000,28.000000,97.000000,7.330000,97.000000,0.800000,4779.405190,4.584371e+06,7.100000,7.200000,0.772000,14.100000,75.600000
max,2015.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.600000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000,89.000000

In [4]:
dataset = dataset.drop(columns = ["Country"], axis = 1)
dataset.head()

,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,2015,Developing,263.0,62,0.01,71.279624,65.0,1154,19.1,83,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,2014,Developing,271.0,64,0.01,73.523582,62.0,492,18.6,86,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,2013,Developing,268.0,66,0.01,73.219243,64.0,430,18.1,89,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,2012,Developing,272.0,69,0.01,78.184215,67.0,2787,17.6,93,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,2011,Developing,275.0,71,0.01,7.097109,68.0,3013,17.2,97,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2

In [5]:
dataset.shape

(2938, 21)

In [6]:
labels = dataset.iloc[:,-1]
labels.head()

0    65.0
1    59.9
2    59.9
3    59.5
4    59.2
Name: Life expectancy, dtype: float64

In [7]:
features = dataset.iloc[:,0:-1]

In [8]:
features = pd.get_dummies(features)
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, train_size = 0.8, random_state = 1)

In [9]:
numerical_features = features.select_dtypes(include=['float64', 'int64'])
numerical_columns = numerical_features.columns

In [10]:
ct = ColumnTransformer([("only numeric", StandardScaler(), numerical_columns)], remainder='passthrough')

features_train_scaled = ct.fit_transform(features_train)
features_test_scaled = ct.fit_transform(features_test)

In [11]:
my_model = Sequential()
my_model.add(layers.InputLayer(input_shape =dataset.shape[1],))
my_model.add(layers.Dense(16, activation = "relu"))
my_model.add(layers.Dense(1))
my_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 16)                352

 dense_1 (Dense)             (None, 1)                 17

=================================================================
Total params: 369
Trainable params: 369
Non-trainable params: 0
_________________________________________________________________

In [12]:
opt = Adam(learning_rate = 0.01)
my_model.compile(optimizer = opt, metrics = ["mae"], loss = "mse")

In [13]:
my_model.fit(features_train_scaled, labels_train, epochs = 40, batch_size = 1, verbose = 1)

Epoch 1/40
2350/2350 [==============================] - 6s 2ms/step - loss: 230.4074 - mae: 7.9986
Epoch 2/40
2350/2350 [==============================] - 5s 2ms/step - loss: 21.3456 - mae: 3.4479
Epoch 3/40
2350/2350 [==============================] - 5s 2ms/step - loss: 18.9800 - mae: 3.2684
Epoch 4/40
2350/2350 [==============================] - 5s 2ms/step - loss: 18.5513 - mae: 3.2273
Epoch 5/40
2350/2350 [==============================] - 5s 2ms/step - loss: 18.8852 - mae: 3.0984
Epoch 6/40
2350/2350 [==============================] - 5s 2ms/step - loss: 14.9826 - mae: 2.8225
Epoch 7/40
2350/2350 [==============================] - 4s 2ms/step - loss: 15.1570 - mae: 2.7397
Epoch 8/40
2350/2350 [==============================] - 5s 2ms/step - loss: 13.6988 - mae: 2.6656
Epoch 9/40
2350/2350 [==============================] - 5s 2ms/step - loss: 12.0883 - mae: 2.5505
Epoch 10/40
2350/2350 [==============================] - 5s 2ms/step - loss: 12.9830 - mae: 2.5144
Epoch 11/40
2350/2350 [==============================] - 6s 2ms/step - loss: 10.2626 - mae: 2.3707
Epoch 12/40
2350/2350 [==============================] - 6s 2ms/step - loss: 12.9285 - mae: 2.4801
Epoch 13/40
2350/2350 [==============================] - 4s 2ms/step - loss: 11.2083 - mae: 2.4863
Epoch 14/40
2350/2350 [==============================] - 5s 2ms/step - loss: 11.4627 - mae: 2.4889
Epoch 15/40
2350/2350 [==============================] - 5s 2ms/step - loss: 10.7934 - mae: 2.4296
Epoch 16/40
2350/2350 [==============================] - 5s 2ms/step - loss: 11.0674 - mae: 2.4579
Epoch 17/40
2350/2350 [==============================] - 5s 2ms/step - loss: 9.7994 - mae: 2.3211
Epoch 18/40
2350/2350 [==============================] - 5s 2ms/step - loss: 10.9874 - mae: 2.3944
Epoch 19/40
2350/2350 [==============================] - 5s 2ms/step - loss: 9.8265 - mae: 2.3551
Epoch 20/40
2350/2350 [==============================] - 5s 2ms/step - loss: 11.0098 - mae: 2.4603
Epoch 21/40
2350/2350 [==============================] - 5s 2ms/step - loss: 10.9116 - mae: 2.3864
Epoch 22/40
2350/2350 [==============================] - 5s 2ms/step - loss: 9.6536 - mae: 2.2609
Epoch 23/40
2350/2350 [==============================] - 5s 2ms/step - loss: 9.7808 - mae: 2.2928
Epoch 24/40
2350/2350 [==============================] - 5s 2ms/step - loss: 10.1594 - mae: 2.3110
Epoch 25/40
2350/2350 [==============================] - 5s 2ms/step - loss: 9.3802 - mae: 2.2759
Epoch 26/40
2350/2350 [==============================] - 5s 2ms/step - loss: 9.5692 - mae: 2.2367
Epoch 27/40
2350/2350 [==============================] - 5s 2ms/step - loss: 9.5927 - mae: 2.2950
Epoch 28/40
2350/2350 [==============================] - 5s 2ms/step - loss: 9.5044 - mae: 2.2512
Epoch 29/40
2350/2350 [==============================] - 5s 2ms/step - loss: 9.1301 - mae: 2.2208
Epoch 30/40
2350/2350 [==============================] - 4s 2ms/step - loss: 9.0892 - mae: 2.2285
Epoch 31/40
2350/2350 [==============================] - 5s 2ms/step - loss: 9.0880 - mae: 2.1833
Epoch 32/40
2350/2350 [==============================] - 5s 2ms/step - loss: 9.9174 - mae: 2.2830
Epoch 33/40
2350/2350 [==============================] - 5s 2ms/step - loss: 8.5978 - mae: 2.1606
Epoch 34/40
2350/2350 [==============================] - 5s 2ms/step - loss: 8.7022 - mae: 2.1697
Epoch 35/40
2350/2350 [==============================] - 4s 2ms/step - loss: 9.3838 - mae: 2.1941
Epoch 36/40
2350/2350 [==============================] - 6s 2ms/step - loss: 8.3734 - mae: 2.1524
Epoch 37/40
2350/2350 [==============================] - 5s 2ms/step - loss: 9.0456 - mae: 2.1911
Epoch 38/40
2350/2350 [==============================] - 5s 2ms/step - loss: 8.4203 - mae: 2.1086
Epoch 39/40
2350/2350 [==============================] - 5s 2ms/step - loss: 8.5634 - mae: 2.1733
Epoch 40/40
2350/2350 [==============================] - 5s 2ms/step - loss: 7.7674 - mae: 2.0356

In [14]:
res_mse,res_mae = my_model.evaluate(features_test_scaled,labels_test )

19/19 [==============================] - 0s 2ms/step - loss: 8.2218 - mae: 2.0937

In [15]:
print(res_mse, res_mae)

8.22181224822998 2.0936567783355713